import { Project, Certificate, Blog } from "@/type";

export const projectData: Project[] = [
  {
    id: "klyro",
    name: "Klyro",
    tagline: "Redis-compatible in-memory database",
    description:
      "Developer-first in-memory database written in Rust. Klyro speaks Redis's RESP protocol and supports familiar data structures, transactions, pub/sub, persistence, eviction policies, and keyword, vector, and hybrid retrieval in the same keyspace.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/klyro/main/images/home.png",
    technologies: [
      "Rust",
      "Redis",
      "RESP",
      "Vector Search",
      "Docker",
      "Nextjs",
      "TypeScript",
      "Python",
      "Go",
    ],
    github: "https://github.com/Hitesh-s0lanki/klyro",
    demo: "https://python-psi-seven.vercel.app",
    ribbon: "New",
    featured: true,
  },
  {
    id: "vec-voice-ai",
    name: "Vec",
    tagline: "Speak, and be answered out loud",
    description:
      "Multilingual voice assistant — speak in any of twenty-two languages and hear a reply about a second after you stop talking. Sarvam's Saaras and Bulbul models handle hearing and speaking, OpenAI writes the replies, and a connectors system lets each user wire in their own vector store, dataset, or tool with no shared corpus.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/voice-vec/main/images/home.png",
    technologies: [
      "Python",
      "FastAPI",
      "Nextjs",
      "TypeScript",
      "Sarvam AI",
      "OpenAI",
      "pgVector",
      "Pinecone",
      "PostgreSQL",
      "Voice AI",
      "RAG",
    ],
    github: "https://github.com/Hitesh-s0lanki/voice-vec",
    ribbon: "New",
    demo: "https://voice-vec.vercel.app",
    featured: true,
  },
  {
    id: "dioramic",
    name: "Dioramic",
    tagline: "Turn a photo into a 3D mesh",
    description:
      "Photo-to-3D web app — upload a picture and a rented GPU turns it into a textured mesh, private to your account. Runs open-source models (TripoSR, Hunyuan3D-2.1, GroundingDINO) on Modal, with photos and meshes in Vercel Blob and every run tracked in Neon Postgres.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/3d-opensource-playground/main/images/home.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Three.js",
      "Python",
      "Clerk",
      "Neon",
      "PostgreSQL",
      "Vercel Blob",
      "Modal",
      "Blender",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/3d-opensource-playground",
    ribbon: "New",
    demo: "https://dioramic.vercel.app",
  },
  {
    id: "relivo-mcp-server",
    name: "Relivo MCP Server",
    tagline: "Multi-namespace MCP server in Go",
    description:
      "Multi-namespace Model Context Protocol server in Go — memory, skills, events, Search Console, and Product Hunt tools mounted on one HTTP mux over Streamable HTTP. Namespaces self-register at startup, and every route is admitted by its own auth: API keys for MCP clients, Clerk for the dashboard.",
    image: "/projects/go-mcp-server.png",
    technologies: [
      "Go",
      "MCP",
      "PostgreSQL",
      "pgVector",
      "Kafka",
      "Nextjs",
      "TypeScript",
      "Clerk",
      "Docker",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/go-mcp-server",
    ribbon: "New",
    demo: "https://go-mcp-server.vercel.app",
    featured: true,
  },
  {
    id: "rumiva",
    name: "Rumiva",
    tagline: "Immersive 3D interior design studio",
    description:
      "Interior design studio experience built for a 3D web hackathon — a React Three Fiber room you explore straight from the hero, plus designer portfolios, project galleries, and service pages tied together with GSAP motion and smooth scrolling.",
    image: "/projects/rumiva.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "React Three Fiber",
      "Three.js",
      "WebGL",
      "GSAP",
      "Tailwind CSS",
      "Shadcn",
    ],
    github: "https://github.com/Hitesh-s0lanki/dream-space-3d",
    ribbon: "New",
    demo: "https://dream-space-3d.vercel.app",
  },
  {
    id: "mindboard-arena",
    name: "MindBoard Arena",
    tagline: "LLM agents play real chess",
    description:
      "Stateful chess arena where language-model agents reason through the board instead of running engine lines — Human vs AI, Human vs Human, and Agent vs Agent modes with persisted games, move history, and match logs.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/mind-board/main/images/home.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "Drizzle",
      "PostgreSQL",
      "LangChain",
      "OpenAI",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/mind-board",
    ribbon: "New",
    demo: "https://mind-board-six.vercel.app",
    featured: true,
  },
  {
    id: "go-ecommerce-api",
    name: "Go E-commerce API",
    tagline: "E-commerce REST API in Go",
    description:
      "E-commerce REST API in Go — JWT auth, product catalog, cart, and orders, with S3 uploads and SQS-backed domain events. Built with gin, GORM, and Postgres.",
    image: "/projects/go.png",
    technologies: [
      "Go",
      "Gin",
      "GORM",
      "PostgreSQL",
      "JWT",
      "AWS S3",
      "AWS SQS",
      "Docker",
      "Swagger",
    ],
    github: "https://github.com/Hitesh-s0lanki/go-ecommerce",
    ribbon: "New",
  },
  {
    id: "resonance",
    name: "Resonance",
    tagline: "Text-to-speech and voice cloning",
    description:
      "AI-powered text-to-speech and voice cloning platform for organisations, with custom voice uploads, browser recording, usage-based billing, and a managed voice library.",
    image: "/projects/resonance-home.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "Clerk",
      "PostgreSQL",
      "Prisma",
      "tRPC",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/resonance",
    ribbon: "New",
    demo: "https://resonance-lilac-gamma.vercel.app",
    featured: true,
  },
  {
    id: "gadgetos",
    name: "GadgetOS",
    tagline: "AI operating system in browser",
    description:
      "AI-powered web operating system with a macOS-inspired desktop — manage files by meaning, run natural language terminal commands via GPT-4.1, and build entirely in the browser.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/gadgetOS/main/public/desktop.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Convex",
      "OpenAI",
      "AWS S3",
      "Tailwind CSS",
      "Zustand",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/gadgetOS",
    ribbon: "New",
    demo: "https://gadget-os-app.vercel.app/",
  },
  {
    id: "bookify",
    name: "Bookify",
    tagline: "AI reading companion for PDFs",
    description:
      "AI-powered reading companion — upload a PDF book, get an AI-generated overview, chat with the content via RAG, and have live voice conversations about it.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/bookify/main/images/home.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Gemini",
      "LangChain",
      "pgVector",
      "AWS S3",
      "Clerk",
      "Vapi",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/bookify",
    ribbon: "New",
    demo: "https://bookify-navy.vercel.app/",
    featured: true,
  },
  {
    id: "ai-story-planner",
    name: "AI Story Planner (Mobile App)",
    tagline: "Plan stories with AI outlines",
    description:
      "AI-powered story planning workspace to structure ideas, generate outlines, and accelerate writing workflows.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/ai-story-planner/main/images/stories-page.png",
    technologies: [
      "React",
      "React Native",
      "TypeScript",
      "Tailwind CSS",
      "OpenAI",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/ai-story-planner",
  },
  {
    id: "streamflow",
    name: "Streamflow",
    tagline: "OTT streaming platform for creators",
    description:
      "OTT streaming platform experience with modern media delivery, discovery UI, and creator-first content workflows.",
    image:
      "https://raw.githubusercontent.com/Hitesh-s0lanki/streamflow/main/images/home.png",
    technologies: [
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "Streaming",
      "Vercel",
    ],
    github: "https://github.com/Hitesh-s0lanki/streamflow",
    demo: "https://streamflow-sigma.vercel.app/",
  },
  {
    id: "ai-auth-agent",
    name: "AI Auth Agent",
    tagline: "Context-preserving AI auth flow",
    description:
      "Context-preserving AI authentication flow focused on reducing login drop-off and improving conversion.",
    image: "/blogs/auth-ai.png",
    technologies: ["Nextjs", "TypeScript", "Tailwind CSS", "Auth", "OpenAI"],
    github: "https://github.com/Hitesh-s0lanki/ai-auth-agent",
  },
  {
    id: "sprintplanner",
    name: "SprintPlanner",
    tagline: "Ideas into four-week ventures",
    description: "Turning your ideas into executable 4-week ventures.",
    image: "/projects/sprintPlanner.png",
    featured: true,
    technologies: [
      "Nextjs",
      "Shadcn",
      "Tailwind CSS",
      "TypeScript",
      "PostgreSQL",
    ],
    github: "https://github.com/Hitesh-s0lanki/sprint-planner-app",
    demo: "https://sprintplanner.xyz",
  },
  {
    id: "ticksy-booking-app",
    name: "Ticksy Booking App",
    tagline: "Event ticketing and booking system",
    description:
      "A booking app for Ticksy, a ticketing system for events and concerts.",
    image: "/projects/ticksy-banner.svg",
    featured: true,
    technologies: [
      "Java",
      "Protobuf",
      "Spring Boot",
      "Python",
      "Razorpay",
      "Agentic",
      "Langchain",
    ],
    github: "https://github.com/Hitesh-s0lanki/ticksy-booking-app",
    demo: "https://ticksy-booking-app.vercel.app/",
  },
  {
    id: "cooksy",
    name: "Cooksy",
    tagline: "AI sous-chef for your pantry",
    description:
      "An AI-powered sous-chef that turns your pantry into mouthwatering recipes—complete with step-by-step instructions, on-brand dish imagery, and curated YouTube video tutorials.",
    image: "/projects/cooksy.png",
    technologies: [
      "Nextjs",
      "React Flow",
      "Tailwind CSS",
      "TypeScript",
      "FastAPI",
      "OpenAI",
      "YouTube API",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/cooksy",
    demo: "https://cooksy-eta.vercel.app/",
  },
  {
    id: "crewai-example",
    name: "CrewAI Example",
    tagline: "Multi-agent reasoning with CrewAI",
    description:
      "A modular, AI-powered platform that uses agent collaboration to automate complex reasoning tasks. Demonstrates CrewAI with real-time streaming, FastAPI backend, and multi-model LLM support.",
    image: "/projects/crew-ai-example.png",
    technologies: [
      "Python",
      "FastAPI",
      "CrewAI",
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "OpenAI",
      "Gemini",
      "SSE",
      "AI Agents",
    ],
    github: "https://github.com/Hitesh-s0lanki/crew_ai_example",
    demo: "https://crew-ai-example.vercel.app",
  },
  {
    id: "shopify-hydrogen-storefront",
    name: "Shopify Hydrogen Storefront",
    tagline: "Shopify Hydrogen storefront for client",
    description: "A Shopify Hydrogen app for a client.",
    image: "/projects/shopify-hydrogen-app.png",
    technologies: [
      "Shopify",
      "Hydrogen",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn",
    ],
    github: "https://github.com/Hitesh-s0lanki/shopify-hydrogen-storefront",
    demo: "https://shopify-hydrogen-storefront-zeta.vercel.app/",
  },
  {
    id: "agentic-blog-generator",
    name: "Agentic Blog Generator",
    tagline: "Blogs written by agent workflows",
    description: "AI-generated blogs via an “agentic” workflow graph.",
    image: "/projects/agentic-blog.png",
    technologies: [
      "AI",
      "Blog",
      "Gen AI",
      "Agents",
      "Nextjs",
      "FastAPI",
      "openai",
    ],
    github: "https://github.com/Hitesh-s0lanki/blog-generator",
    demo: "https://blog-generator-tau.vercel.app/",
  },
  {
    id: "agentic-ai-use-cases",
    name: "Agent AI Use-cases Example",
    tagline: "Agentic AI use-case playground",
    description:
      "A Streamlit-powered application showcasing multiple agentic AI use cases using LangGraph, Tavily, OpenAI, Groq, and LangChain.",
    image: "/projects/news_ai.png",
    technologies: [
      "AI",
      "Chat",
      "AI News",
      "Agents",
      "Tavily",
      "Langgraph",
      "Python",
      "Streamlit",
      "openai",
      "groq",
    ],
    github: "https://github.com/Hitesh-s0lanki/agentic-ai-chatbot",
    demo: "https://hitesh-s0lanki-agentic-ai-chatbot-app-1sl3to.streamlit.app/",
  },
  {
    id: "meet-ai",
    name: "Meet AI",
    tagline: "Video meetings with AI agents",
    description:
      "A real-time, AI-powered video & chat platform—create your own AI “agents,” schedule meetings, and collaborate seamlessly in the browser.",
    image: "/projects/meet-with-agent.png",
    technologies: [
      "AI",
      "Chat",
      "Transcript",
      "Agents",
      "Meet",
      "Nextjs",
      "Stream",
      "openai",
      "inngest",
    ],
    github: "https://github.com/Hitesh-s0lanki/meet-ai",
    demo: "https://meet-ai-plum.vercel.app/",
  },
  {
    id: "webinar-ai",
    name: "Webinar AI",
    tagline: "AI webinars that convert leads",
    description:
      "Welcome to Webinar AI, an AI-powered platform that helps you create, manage, and automate webinars — designed to maximize lead generation and conversion using intelligent agents.",
    image: "/projects/webinar.png",
    technologies: [
      "AI",
      "Agents",
      "Webinar",
      "Nextjs",
      "Stream",
      "openai",
      "Conversions",
      "Vapi AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/ai-sales-agent",
  },
  {
    id: "react-agent",
    name: "ReAct Agent ",
    tagline: "ReAct agent with real tools",
    description:
      "This project demonstrates a ReAct (Reason + Act) agent implemented using LangChain, integrated with real-world tools like Arxiv, Wikipedia, and Tavily to search, reason, and respond to complex user queries.",
    image: "/projects/reAct.png",
    technologies: [
      "AI",
      "Agents",
      "Tools",
      "Arxiv",
      "Wikipedia",
      "Tavily",
      "Python",
    ],
    github: "https://github.com/Hitesh-s0lanki/ReAct-agent-with-multi-tools",
    demo: "https://re-act-agent-with-multi-tools.vercel.app/",
  },
  {
    id: "agentic-ai",
    name: "Agentic AI",
    tagline: "LangGraph agent workflows, hands-on",
    description:
      "Learn to build real-world AI agents, multi-agent workflows, and autonomous apps with LangGraph and LangChain",
    image: "/projects/agentic-ai.png",
    technologies: [
      "AI",
      "ReAct Agent",
      "Tool Agent",
      "Agentic Rag",
      "langchain",
      "langgraph",
      "langserve",
      "openai",
      "Advance Python",
    ],
    github: "https://github.com/Hitesh-s0lanki/GenAI-AgentAI",
    ribbon: "Hot",
  },
  {
    id: "space-on-hire",
    name: "Space On Hire",
    tagline: "AI platform for outdoor advertising",
    description:
      "An AI-powered platform to streamline outdoor advertising assets, bookings, analytics, and CRM operations.",
    image: "/projects/space-on-hire.png",
    technologies: ["Nextjs", "OOH", "CRM", "Analytics", "AI", "Customer"],
    github: "https://github.com/Hitesh-s0lanki/space-on-hire",
    demo: "https://space-on-hire.vercel.app/",
    ribbon: "New",
  },
  {
    id: "gadgetos-web-os",
    name: "GadgetOS",
    tagline: "Desktop experience inside the browser",
    description:
      "Browser-based operating system built to simulate a desktop-like experience entirely within your browser.",
    image: "/projects/gadgetOS.png",
    technologies: ["Nextjs", "Convex", "Real-time", "terminal", "openai", "ai"],
    github: "https://github.com/Hitesh-s0lanki/gadgetOS/tree/web_os",
    demo: "https://gadget-os-app.vercel.app/",
  },
  {
    id: "kya-banana-hai",
    name: "Kya Banana Hai",
    tagline: "Smart kitchen assistant for cooking",
    description:
      "A smart kitchen assistant that helps you decide what food to cook based on ingredients, time, and mood — powered by AI.",
    image: "/projects/kyabananahai.png",
    technologies: ["Nextjs", "Convex", "Real-time", "terminal", "openai", "ai"],
    github: "https://github.com/Hitesh-s0lanki/kya-banana-hai-app-fe",
    demo: "https://kya-banana-hai-app-fe.vercel.app/",
  },
  {
    id: "ai-crm-26ideas",
    name: "AI-CRM Platform - 26ideas",
    tagline: "AI CRM on microservices",
    description:
      "An AI-powered CRM platform designed to streamline operations by centralizing contacts, jobs, candidates, companies, and ideas.",
    image: "/projects/crm26ideas.png",
    technologies: [
      "Nextjs",
      "Nestjs",
      "Microservice",
      "Shadcn",
      "Postgres",
      "Suprabase",
      "openai",
      "Google",
    ],
    github: "https://github.com/Hitesh-s0lanki/microservice-ai-crm",
  },
  {
    id: "shortify",
    name: "Shortify",
    tagline: "URL shortener on Spring, AWS",
    description:
      "A full-stack URL shortener built with React, Spring, Java, MySQL, Docker, and AWS ECS.",
    image: "/projects/url-shortener-home.png",
    technologies: [
      "Reactjs",
      "Spring",
      "Spring Framework",
      "Java",
      "MySQL",
      "Spring Security",
      "Typescript",
      "Docker",
      "ECS",
    ],
    github: "https://github.com/Hitesh-s0lanki/url-shortener",
  },
  {
    id: "codetech",
    name: "Codetech",
    tagline: "Coding challenges with live compiler",
    description:
      "Interactive coding challenge platform with file-based execution, code compiler, and Firebase auth.",
    image: "/projects/codetech.png",
    technologies: ["React", "Firebase", "file", "code compiler", "leetcode"],
    github: "https://github.com/Hitesh-s0lanki/codetech_new",
    demo: "https://codetech-new.vercel.app",
  },
  {
    id: "tic-tac-toe-ai",
    name: "🎮 Tic Tac Toe AI",
    tagline: "Tic tac toe, unbeatable minimax",
    description:
      "Tic Tac Toe with Player vs Player & Player vs AI mode. AI uses Minimax for perfect play.",
    image: "/projects/tictactoe.png",
    technologies: ["Python", "Pygame", "Minimax", "Algorithm", "AI"],
    github: "https://github.com/Hitesh-s0lanki/TicTacToeAi",
  },
  {
    id: "chess-python-pygame",
    name: "♟️ Chess (Python + Pygame)",
    tagline: "Drag-and-drop chess in Pygame",
    description:
      "A visually interactive chess engine with drag-and-drop movement and theming.",
    image: "/projects/pythonchess.png",
    technologies: ["Python", "Pygame", "Drag N Drop", "Chess"],
    github: "https://github.com/Hitesh-s0lanki/ChessAi",
  },
  {
    id: "email-reply-generator",
    name: "Email Reply Generator",
    tagline: "AI email replies in Chrome",
    description:
      "AI-powered professional email reply generator with Chrome extension support.",
    image: "/projects/email-writer-app.png",
    technologies: [
      "Reactjs",
      "Typescript",
      "Vite",
      "Spring Boot",
      "Java",
      "Shadcn",
      "Gemini",
      "Chrome Extension",
    ],
    github: "https://github.com/Hitesh-s0lanki/email-reply-generator",
  },
  {
    id: "research-assistant-chrome-extension",
    name: "Research Assistant - Chrome Extension",
    tagline: "Summarise and save any selection",
    description:
      "Chrome extension to summarize selected text instantly and store notes.",
    image: "/projects/research-assistant.png",
    technologies: [
      "Spring Boot",
      "Spring MVC",
      "Java",
      "Shadcn",
      "Gemini",
      "Chrome Extension",
    ],
    github: "https://github.com/Hitesh-s0lanki/research-assistant-chromer",
  },
  {
    id: "inventory-management",
    name: "Inventory Management",
    tagline: "Inventory system on AWS infrastructure",
    description:
      "Full-stack inventory system deployed on AWS with secure, scalable cloud infra.",
    image: "/projects/inventory.png",
    technologies: [
      "Nextjs",
      "Node.js",
      "Redux",
      "Shadcn",
      "AWS",
      "RDS",
      "NAT",
      "VPC",
      "EC2",
      "API Gateway",
    ],
    github: "https://github.com/Hitesh-s0lanki/inventory-management",
    demo: "https://main.d1az7sps7yw18.amplifyapp.com/",
  },
  {
    id: "ai-saas",
    name: "AI-Saas",
    tagline: "Chat, image, video, code generation",
    description:
      "AI-powered SaaS dashboard with chat, images, video, audio and code generation.",
    image: "/projects/ai-saas.png",
    technologies: ["Nextjs", "Shadcn", "OPENAI"],
    github: "https://github.com/Hitesh-s0lanki/ai-saas",
    demo: "https://ai-saas-ruby-theta.vercel.app/",
  },
  {
    id: "statistics-dashboard",
    name: "Statistics Dashboard",
    tagline: "Descriptive statistics, computed live",
    description:
      "React/Next.js dashboard for computing descriptive statistics with smooth UI.",
    image: "/projects/mean-median-mode.png",
    technologies: ["Nextjs", "Shadcn", "Math", "Statistics"],
    github: "https://github.com/Hitesh-s0lanki/mean-median-mode",
    demo: "https://mean-median-mode-alpha.vercel.app/",
  },
  {
    id: "chess-web",
    name: "Chess Web",
    tagline: "Chess built with vanilla JavaScript",
    description: "Chess game built using HTML, CSS, and JavaScript.",
    image: "/projects/chess-web.png",
    technologies: ["HTML", "CSS", "Javascript"],
    github: "https://github.com/Hitesh-s0lanki/Chess-Project",
    demo: "https://chess-project.vercel.app/",
  },
  {
    id: "storeit",
    name: "StoreIt",
    tagline: "Cloud file storage, Drive-style",
    description:
      "Cloud-based file storage app replicating Google Drive core features.",
    image: "/projects/storeit.png",
    technologies: ["Nextjs", "appwrite", "Vercel", "file Management"],
    github: "https://github.com/Hitesh-s0lanki/drive-clone",
    demo: "https://drive-clone-seven.vercel.app/",
  },
  {
    id: "miro-clone",
    name: "Miro",
    tagline: "Real-time collaborative whiteboard",
    description:
      "Real-time collaborative whiteboard with Liveblocks, Next.js, and Clerk.",
    image: "/projects/miro.png",
    technologies: ["Nextjs", "liveblocks", "Vercel", "Clerk"],
    github: "https://github.com/Hitesh-s0lanki/miro-app",
    demo: "https://miro-app-psi.vercel.app/",
  },
  {
    id: "todovex",
    name: "Todovex",
    tagline: "AI-powered task management app",
    description: "AI-powered task management app.",
    image: "/projects/todovex.png",
    technologies: ["Nextjs", "convex", "openai", "Vercel"],
    github: "https://github.com/Hitesh-s0lanki/todovex",
    demo: "https://todovex.vercel.app/",
  },

  {
    id: "26ideas",
    name: "26ideas",
    tagline: "Company website for 26ideas",
    description: "Company Oriented",
    image: "/projects/26ideas.png",
    technologies: ["Nextjs", "static", "26ideas"],
    demo: "https://www.26ideas.com/",
  },
  {
    id: "data-structures",
    name: "Data Structure",
    tagline: "Data structures and LeetCode solutions",
    description:
      "Collection of DS implementations paired with LeetCode solutions.",
    image: "/projects/data-structure.png",
    technologies: ["Array", "Graph", "linked list", "Tree", "BST", "Sorting"],
    github: "https://github.com/Hitesh-s0lanki/DSALeetcode",
  },
  {
    id: "terraform-iaac",
    name: "Terraform IAAC",
    tagline: "Terraform IaC for AWS provisioning",
    description: "Terraform IaC framework for automated AWS provisioning.",
    image: "/projects/terraform.png",
    technologies: ["Terraform", "AWS", "GitHub Actions"],
    github: "https://github.com/Hitesh-s0lanki/terraform-iaac-vprofile",
  },
];

/** Projects surfaced on the home page carousel, in display order. */
export const featuredProjects = projectData.filter(
  (project) => project.featured,
);

/** Look up a project by its slug — the segment of /projects/{id}. */
export const getProjectById = (id: string) =>
  projectData.find((project) => project.id === id);

/**
 * Other projects to suggest at the bottom of a project page: the ones sharing
 * the most technologies, so the recommendation is never arbitrary.
 */
export const getRelatedProjects = (project: Project, limit = 3) => {
  const stack = new Set(project.technologies.map((tech) => tech.toLowerCase()));

  return projectData
    .filter((candidate) => candidate.id !== project.id)
    .map((candidate) => ({
      candidate,
      overlap: candidate.technologies.filter((tech) =>
        stack.has(tech.toLowerCase()),
      ).length,
    }))
    .sort((a, b) => b.overlap - a.overlap)
    .slice(0, limit)
    .map(({ candidate }) => candidate);
};

export const certificates: Certificate[] = [
  {
    id: 8,
    name: "Complete C# Masterclass",
    issuer: "Udemy",
    date: "2026",
    image: "/certificates/UC-901f3bd2-34bd-4c81-9035-df5e5e15af43.jpg",
    category: ["C#", ".NET", "OOP", "Backend"],
    link: "https://ude.my/UC-901f3bd2-34bd-4c81-9035-df5e5e15af43",
  },
  {
    id: 7,
    name: "Go (Golang) Masterclass: Learn Like a Google Engineer",
    issuer: "Udemy",
    date: "2026",
    image: "/certificates/go.jpg",
    category: [
      "Go",
      "Golang",
      "Concurrency",
      "Goroutines",
      "REST API",
      "Backend",
    ],
  },
  {
    id: 4,
    name: "Complete Agentic AI Bootcamp With LangGraph and Langchain",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/agentic-ai.jpg",
    category: [
      "AI",
      "ReAct Agent",
      "Tool Agent",
      "Agentic Rag",
      "langchain",
      "langgraph",
      "langserve",
      "openai",
      "Advance Python",
    ],
  },
  {
    id: 5,
    name: "gRPC Masterclass with Java & Spring Boot [ Hands-On]",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/gRPC.jpg",
    category: ["gRPC", "Protobuf", "Java", "Spring"],
  },
  {
    id: 6,
    name: "Complete Guide to Protocol Buffers 3 [Java, Golang, Python]",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/protobuf-certificate.jpg",
    category: ["Protocol Buffer", "Google", "Java", "Gradle", "Maven"],
  },
  {
    id: 1,
    name: "Java Spring Framework 6 with Spring Boot 3",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/java.png",
    category: [
      "Spring",
      "Spring Boot",
      "Core Java",
      "JPA",
      "Hibernate",
      "JSP",
      "JWT",
    ],
  },
  {
    id: 2,
    name: "DevOps Engineer",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/devops.jpeg",
    category: [
      "DevOps",
      "CI/CD",
      "Jenkins",
      "Ansible",
      "Github",
      "Docker",
      "Kubernates",
      "AWS",
      "linux",
      "Vagrant",
    ],
  },
  {
    id: 3,
    name: "MEDDICC MEDDPICC Sales training",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/sales.png",
    category: ["Sales"],
  },
];

export const blogsData: Blog[] = [
  {
    id: 1,
    title:
      "Building a Multi-Stage Agentic AI System with LangChain: SprintPlanner Case Study",
    url: "https://medium.com/@hiteshsolanki4623/building-a-multi-stage-agentic-ai-system-with-langchain-sprintplanner-case-study-ff923a04e3ac",
    description:
      "Learn how to build a multi-stage agentic AI system using LangChain with a real-world case study of SprintPlanner.",
    image: "/blogs/multi-stage.png",
    tags: ["LangChain", "Next.js", "Tailwind CSS", "TypeScript", "OpenAI"],
  },
  {
    id: 2,
    title:
      "How I Built an AI-Powered Shopify Storefront That Talks Like a Human",
    url: "https://medium.com/@hiteshsolanki4623/how-i-built-an-ai-powered-shopify-storefront-that-talks-like-a-human-ce81d835fb90",
    description:
      "Discover how to create an AI-powered Shopify storefront with natural human-like conversations.",
    image: "/projects/shopify-hydrogen-app.png",
    tags: ["Shopify", "Next.js", "Tailwind CSS", "TypeScript", "OpenAI"],
  },
  {
    id: 3,
    title:
      "Stop Losing Users at Login: How Context-Preserving AI Auth Agents Reduce Drop-off",
    url: "https://medium.com/@hiteshsolanki4623/stop-losing-users-at-login-how-context-preserving-ai-auth-agents-reduce-drop-off-3cc54325f62e",
    description:
      "A practical breakdown of building context-preserving AI auth flows that reduce login drop-off and improve conversion.",
    image: "/blogs/auth-ai.png",
    tags: ["Next.js", "TypeScript", "OpenAI", "Tailwind CSS", "Auth"],
  },
  {
    id: 4,
    title: "From One Instagram Reel to a Full OTT Streaming Platform",
    url: "https://medium.com/@hiteshsolanki4623/from-one-instagram-reel-to-a-full-ott-streaming-platform-d1e0ee28c513",
    description:
      "How a single short-form content idea evolved into a complete OTT platform, from architecture to product execution.",
    image: "https://streamflow-sigma.vercel.app/sprite.jpg",
    tags: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Streaming"],
  },
];
