import { Project, Certificate, Blog } from "@/type";

export const projectData: Project[] = [
  {
    id: 30,
    name: "SprintPlanner",
    description: "Turning your ideas into executable 4-week ventures.",
    image: "/projects/sprintPlanner.png",
    featured: true,
    technologies: [
      "Nextjs",
      "Shadcn",
      "Tailwind CSS",
      "TypeScript",
      "PostgreSQL",
    ],
    github: "https://github.com/Hitesh-s0lanki/sprint-planner-app",
    demo: "https://sprintplanner.xyz",
  },
  {
    id: 29,
    name: "Ticksy Booking App",
    description:
      "A booking app for Ticksy, a ticketing system for events and concerts.",
    image: "/projects/ticksy-banner.svg",
    featured: true,
    technologies: [
      "Java",
      "Protobuf",
      "Spring Boot",
      "Python",
      "Razorpay",
      "Agentic",
      "Langchain",
    ],
    github: "https://github.com/Hitesh-s0lanki/ticksy-booking-app",
    demo: "https://ticksy-booking-app.vercel.app/",
  },
  {
    id: 28,
    name: "Cooksy",
    description:
      "An AI-powered sous-chef that turns your pantry into mouthwatering recipes—complete with step-by-step instructions, on-brand dish imagery, and curated YouTube video tutorials.",
    image: "/projects/cooksy.png",
    featured: true,
    technologies: [
      "Nextjs",
      "React Flow",
      "Tailwind CSS",
      "TypeScript",
      "FastAPI",
      "OpenAI",
      "YouTube API",
      "AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/cooksy",
    demo: "https://cooksy-eta.vercel.app/",
  },
  {
    id: 27,
    name: "CrewAI Example",
    description:
      "A modular, AI-powered platform that uses agent collaboration to automate complex reasoning tasks. Demonstrates CrewAI with real-time streaming, FastAPI backend, and multi-model LLM support.",
    image: "/projects/crew-ai-example.png",
    featured: true,
    technologies: [
      "Python",
      "FastAPI",
      "CrewAI",
      "Nextjs",
      "TypeScript",
      "Tailwind CSS",
      "OpenAI",
      "Gemini",
      "SSE",
      "AI Agents",
    ],
    github: "https://github.com/Hitesh-s0lanki/crew_ai_example",
    demo: "https://crew-ai-example.vercel.app",
  },
  {
    id: 26,
    name: "Shopify Hydrogen Storefront",
    description: "A Shopify Hydrogen app for a client.",
    image: "/projects/shopify-hydrogen-app.png",
    technologies: [
      "Shopify",
      "Hydrogen",
      "React",
      "TypeScript",
      "Tailwind CSS",
      "Shadcn",
    ],
    github: "https://github.com/Hitesh-s0lanki/shopify-hydrogen-storefront",
    demo: "https://shopify-hydrogen-storefront-zeta.vercel.app/",
  },
  {
    id: 25,
    name: "Agentic Blog Generator",
    description: "AI-generated blogs via an “agentic” workflow graph.",
    image: "/projects/agentic-blog.png",
    technologies: [
      "AI",
      "Blog",
      "Gen AI",
      "Agents",
      "Nextjs",
      "FastAPI",
      "openai",
    ],
    github: "https://github.com/Hitesh-s0lanki/blog-generator",
    demo: "https://blog-generator-tau.vercel.app/",
  },
  {
    id: 24,
    name: "Agent AI Use-cases Example",
    description:
      "A Streamlit-powered application showcasing multiple agentic AI use cases using LangGraph, Tavily, OpenAI, Groq, and LangChain.",
    image: "/projects/news_ai.png",
    technologies: [
      "AI",
      "Chat",
      "AI News",
      "Agents",
      "Tavily",
      "Langgraph",
      "Python",
      "Streamlit",
      "openai",
      "groq",
    ],
    github: "https://github.com/Hitesh-s0lanki/agentic-ai-chatbot",
    demo: "https://hitesh-s0lanki-agentic-ai-chatbot-app-1sl3to.streamlit.app/",
  },
  {
    id: 23,
    name: "Meet AI",
    description:
      "A real-time, AI-powered video & chat platform—create your own AI “agents,” schedule meetings, and collaborate seamlessly in the browser.",
    image: "/projects/meet-with-agent.png",
    technologies: [
      "AI",
      "Chat",
      "Transcript",
      "Agents",
      "Meet",
      "Nextjs",
      "Stream",
      "openai",
      "inngest",
    ],
    github: "https://github.com/Hitesh-s0lanki/meet-ai",
    demo: "https://meet-ai-plum.vercel.app/",
  },
  {
    id: 22,
    name: "Webinar AI",
    description:
      "Welcome to Webinar AI, an AI-powered platform that helps you create, manage, and automate webinars — designed to maximize lead generation and conversion using intelligent agents.",
    image: "/projects/webinar.png",
    technologies: [
      "AI",
      "Agents",
      "Webinar",
      "Nextjs",
      "Stream",
      "openai",
      "Conversions",
      "Vapi AI",
    ],
    github: "https://github.com/Hitesh-s0lanki/ai-sales-agent",
  },
  {
    id: 21,
    name: "ReAct Agent ",
    description:
      "This project demonstrates a ReAct (Reason + Act) agent implemented using LangChain, integrated with real-world tools like Arxiv, Wikipedia, and Tavily to search, reason, and respond to complex user queries.",
    image: "/projects/reAct.png",
    technologies: [
      "AI",
      "Agents",
      "Tools",
      "Arxiv",
      "Wikipedia",
      "Tavily",
      "Python",
    ],
    github: "https://github.com/Hitesh-s0lanki/ReAct-agent-with-multi-tools",
    demo: "https://re-act-agent-with-multi-tools.vercel.app/",
  },
  {
    id: 20,
    name: "Agentic AI",
    description:
      "Learn to build real-world AI agents, multi-agent workflows, and autonomous apps with LangGraph and LangChain",
    image: "/projects/agentic-ai.png",
    technologies: [
      "AI",
      "ReAct Agent",
      "Tool Agent",
      "Agentic Rag",
      "langchain",
      "langgraph",
      "langserve",
      "openai",
      "Advance Python",
    ],
    github: "https://github.com/Hitesh-s0lanki/GenAI-AgentAI",
    ribbon: "Hot",
  },
  {
    id: 19,
    name: "Space On Hire",
    description:
      "An AI-powered platform to streamline outdoor advertising assets, bookings, analytics, and CRM operations.",
    image: "/projects/space-on-hire.png",
    technologies: ["Nextjs", "OOH", "CRM", "Analytics", "AI", "Customer"],
    github: "https://github.com/Hitesh-s0lanki/space-on-hire",
    demo: "https://space-on-hire.vercel.app/",
    ribbon: "New",
  },
  {
    id: 18,
    name: "GadgetOS",
    description:
      "Browser-based operating system built to simulate a desktop-like experience entirely within your browser.",
    image: "/projects/gadgetOS.png",
    technologies: ["Nextjs", "Convex", "Real-time", "terminal", "openai", "ai"],
    github: "https://github.com/Hitesh-s0lanki/gadgetOS/tree/web_os",
    demo: "https://gadgetos.in/",
  },
  {
    id: 17,
    name: "Kya Banana Hai",
    description:
      "A smart kitchen assistant that helps you decide what food to cook based on ingredients, time, and mood — powered by AI.",
    image: "/projects/kyabananahai.png",
    technologies: ["Nextjs", "Convex", "Real-time", "terminal", "openai", "ai"],
    github: "https://github.com/Hitesh-s0lanki/kya-banana-hai-app-fe",
    demo: "https://kya-banana-hai-app-fe.vercel.app/",
  },
  {
    id: 16,
    name: "AI-CRM Platform - 26ideas",
    description:
      "An AI-powered CRM platform designed to streamline operations by centralizing contacts, jobs, candidates, companies, and ideas.",
    image: "/projects/crm26ideas.png",
    technologies: [
      "Nextjs",
      "Nestjs",
      "Microservice",
      "Shadcn",
      "Postgres",
      "Suprabase",
      "openai",
      "Google",
    ],
    github: "https://github.com/Hitesh-s0lanki/microservice-ai-crm",
  },
  {
    id: 15,
    name: "Shortify",
    description:
      "A full-stack URL shortener built with React, Spring, Java, MySQL, Docker, and AWS ECS.",
    image: "/projects/url-shortener-home.png",
    technologies: [
      "Reactjs",
      "Spring",
      "Spring Framework",
      "Java",
      "MySQL",
      "Spring Security",
      "Typescript",
      "Docker",
      "ECS",
    ],
    github: "https://github.com/Hitesh-s0lanki/url-shortener",
  },
  {
    id: 14,
    name: "Codetech",
    description:
      "Interactive coding challenge platform with file-based execution, code compiler, and Firebase auth.",
    image: "/projects/codetech.png",
    technologies: ["React", "Firebase", "file", "code compiler", "leetcode"],
    github: "https://github.com/Hitesh-s0lanki/codetech_new",
    demo: "https://codetech-new.vercel.app",
  },
  {
    id: 13,
    name: "🎮 Tic Tac Toe AI",
    description:
      "Tic Tac Toe with Player vs Player & Player vs AI mode. AI uses Minimax for perfect play.",
    image: "/projects/tictactoe.png",
    technologies: ["Python", "Pygame", "Minimax", "Algorithm", "AI"],
    github: "https://github.com/Hitesh-s0lanki/TicTacToeAi",
  },
  {
    id: 12,
    name: "♟️ Chess (Python + Pygame)",
    description:
      "A visually interactive chess engine with drag-and-drop movement and theming.",
    image: "/projects/pythonchess.png",
    technologies: ["Python", "Pygame", "Drag N Drop", "Chess"],
    github: "https://github.com/Hitesh-s0lanki/ChessAi",
  },
  {
    id: 11,
    name: "Email Reply Generator",
    description:
      "AI-powered professional email reply generator with Chrome extension support.",
    image: "/projects/email-writer-app.png",
    technologies: [
      "Reactjs",
      "Typescript",
      "Vite",
      "Spring Boot",
      "Java",
      "Shadcn",
      "Gemini",
      "Chrome Extension",
    ],
    github: "https://github.com/Hitesh-s0lanki/email-reply-generator",
  },
  {
    id: 10,
    name: "Research Assistant - Chrome Extension",
    description:
      "Chrome extension to summarize selected text instantly and store notes.",
    image: "/projects/research-assistant.png",
    technologies: [
      "Spring Boot",
      "Spring MVC",
      "Java",
      "Shadcn",
      "Gemini",
      "Chrome Extension",
    ],
    github: "https://github.com/Hitesh-s0lanki/research-assistant-chromer",
  },
  {
    id: 9,
    name: "Inventory Management",
    description:
      "Full-stack inventory system deployed on AWS with secure, scalable cloud infra.",
    image: "/projects/inventory.png",
    technologies: [
      "Nextjs",
      "Node.js",
      "Redux",
      "Shadcn",
      "AWS",
      "RDS",
      "NAT",
      "VPC",
      "EC2",
      "API Gateway",
    ],
    github: "https://github.com/Hitesh-s0lanki/inventory-management",
    demo: "https://main.d1az7sps7yw18.amplifyapp.com/",
  },
  {
    id: 8,
    name: "AI-Saas",
    description:
      "AI-powered SaaS dashboard with chat, images, video, audio and code generation.",
    image: "/projects/ai-saas.png",
    technologies: ["Nextjs", "Shadcn", "OPENAI"],
    github: "https://github.com/Hitesh-s0lanki/ai-saas",
    demo: "https://ai-saas-ruby-theta.vercel.app/",
  },
  {
    id: 7,
    name: "Statistics Dashboard",
    description:
      "React/Next.js dashboard for computing descriptive statistics with smooth UI.",
    image: "/projects/mean-median-mode.png",
    technologies: ["Nextjs", "Shadcn", "Math", "Statistics"],
    github: "https://github.com/Hitesh-s0lanki/mean-median-mode",
    demo: "https://mean-median-mode-alpha.vercel.app/",
  },
  {
    id: 6,
    name: "Chess Web",
    description: "Chess game built using HTML, CSS, and JavaScript.",
    image: "/projects/chess-web.png",
    technologies: ["HTML", "CSS", "Javascript"],
    github: "https://github.com/Hitesh-s0lanki/Chess-Project",
    demo: "https://chess-project.vercel.app/",
  },
  {
    id: 5,
    name: "StoreIt",
    description:
      "Cloud-based file storage app replicating Google Drive core features.",
    image: "/projects/storeit.png",
    technologies: ["Nextjs", "appwrite", "Vercel", "file Management"],
    github: "https://github.com/Hitesh-s0lanki/drive-clone",
    demo: "https://drive-clone-seven.vercel.app/",
  },
  {
    id: 4,
    name: "Miro",
    description:
      "Real-time collaborative whiteboard with Liveblocks, Next.js, and Clerk.",
    image: "/projects/miro.png",
    technologies: ["Nextjs", "liveblocks", "Vercel", "Clerk"],
    github: "https://github.com/Hitesh-s0lanki/miro-app",
    demo: "https://miro-app-psi.vercel.app/",
  },
  {
    id: 3,
    name: "Todovex",
    description: "AI-powered task management app.",
    image: "/projects/todovex.png",
    technologies: ["Nextjs", "convex", "openai", "Vercel"],
    github: "https://github.com/Hitesh-s0lanki/todovex",
    demo: "https://todovex.vercel.app/",
  },

  {
    id: 2,
    name: "26ideas",
    description: "Company Oriented",
    image: "/projects/26ideas.png",
    technologies: ["Nextjs", "static", "26ideas"],
    demo: "https://www.26ideas.com/",
  },
  {
    id: 1,
    name: "Data Structure",
    description:
      "Collection of DS implementations paired with LeetCode solutions.",
    image: "/projects/data-structure.png",
    technologies: ["Array", "Graph", "linked list", "Tree", "BST", "Sorting"],
    github: "https://github.com/Hitesh-s0lanki/DSALeetcode",
  },
  {
    id: 0,
    name: "Terraform IAAC",
    description: "Terraform IaC framework for automated AWS provisioning.",
    image: "/projects/terraform.png",
    technologies: ["Terraform", "AWS", "GitHub Actions"],
    github: "https://github.com/Hitesh-s0lanki/terraform-iaac-vprofile",
  },
];

export const certificates: Certificate[] = [
  {
    id: 4,
    name: "Complete Agentic AI Bootcamp With LangGraph and Langchain",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/agentic-ai.jpg",
    category: [
      "AI",
      "ReAct Agent",
      "Tool Agent",
      "Agentic Rag",
      "langchain",
      "langgraph",
      "langserve",
      "openai",
      "Advance Python",
    ],
  },
  {
    id: 5,
    name: "gRPC Masterclass with Java & Spring Boot [ Hands-On]",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/gRPC.jpg",
    category: ["gRPC", "Protobuf", "Java", "Spring"],
  },
  {
    id: 6,
    name: "Complete Guide to Protocol Buffers 3 [Java, Golang, Python]",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/protobuf-certificate.jpg",
    category: ["Protocol Buffer", "Google", "Java", "Gradle", "Maven"],
  },
  {
    id: 1,
    name: "Java Spring Framework 6 with Spring Boot 3",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/java.png",
    category: [
      "Spring",
      "Spring Boot",
      "Core Java",
      "JPA",
      "Hibernate",
      "JSP",
      "JWT",
    ],
  },
  {
    id: 2,
    name: "DevOps Engineer",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/devops.jpeg",
    category: [
      "DevOps",
      "CI/CD",
      "Jenkins",
      "Ansible",
      "Github",
      "Docker",
      "Kubernates",
      "AWS",
      "linux",
      "Vagrant",
    ],
  },
  {
    id: 3,
    name: "MEDDICC MEDDPICC Sales training",
    issuer: "Udemy",
    date: "2025",
    image: "/certificates/sales.png",
    category: ["Sales"],
  },
];

export const blogsData: Blog[] = [
  {
    id: 1,
    title:
      "Building a Multi-Stage Agentic AI System with LangChain: SprintPlanner Case Study",
    url: "https://medium.com/@hiteshsolanki4623/building-a-multi-stage-agentic-ai-system-with-langchain-sprintplanner-case-study-ff923a04e3ac",
    description:
      "Learn how to build a multi-stage agentic AI system using LangChain with a real-world case study of SprintPlanner.",
  },
  {
    id: 2,
    title:
      "How I Built an AI-Powered Shopify Storefront That Talks Like a Human",
    url: "https://medium.com/@hiteshsolanki4623/how-i-built-an-ai-powered-shopify-storefront-that-talks-like-a-human-ce81d835fb90",
    description:
      "Discover how to create an AI-powered Shopify storefront with natural human-like conversations.",
  },
];
